const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const { jobs, upload, COMPRESSED_DIR, execGhostscript, getGsDiagnosticInfo, isValidPdfHeader } = require('./config');

// Diagnostics Endpoint
router.get('/diagnostics', (req, res) => {
  res.json(getGsDiagnosticInfo());
});

// Compress PDF Endpoint
router.post('/compress', upload.single('pdf'), async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No PDF file was uploaded.' });
  }

  const inputPath = req.file.path;

  // Validate PDF magic header to prevent processing non-PDF / malicious files
  const isValidPdf = await isValidPdfHeader(inputPath);
  if (!isValidPdf) {
    if (fs.existsSync(inputPath)) {
      try {
        await fs.promises.unlink(inputPath);
      } catch (e) {}
    }
    return res.status(400).json({ error: 'The uploaded file is not a valid PDF document.' });
  }

  // Validate preset against strict whitelist to prevent parameter injection
  const VALID_PRESETS = ['screen', 'ebook', 'printer', 'prepress', 'default'];
  const preset = VALID_PRESETS.includes(req.body.preset) ? req.body.preset : 'ebook';

  const originalName = req.file.originalname;
  const originalSize = req.file.size;
  const jobId = req.file.filename;

  jobs[jobId] = {
    status: 'processing',
    timestamp: Date.now()
  };

  res.json({
    success: true,
    status: 'processing',
    jobId: jobId
  });

  const compressedFilename = `compressed-${path.basename(req.file.filename)}`;
  const outputPath = path.join(COMPRESSED_DIR, compressedFilename);

  const gsArgs = [
    '-sDEVICE=pdfwrite',
    '-dCompatibilityLevel=1.4',
    '-dSAFER',
    `-dPDFSETTINGS=/${preset}`,
    '-dNOPAUSE',
    '-dQUIET',
    '-dBATCH',
    `-sOutputFile=${outputPath}`,
    inputPath
  ];

  const handleResult = (err) => {
    if (fs.existsSync(inputPath)) {
      try {
        fs.unlinkSync(inputPath);
      } catch (e) {}
    }

    if (err) {
      console.error(`[ERROR] Ghostscript failed for job ${jobId}:`, err);
      jobs[jobId] = {
        status: 'error',
        error: err.message || 'Ghostscript compression failed.',
        timestamp: Date.now()
      };
      return;
    }

    if (!fs.existsSync(outputPath)) {
      jobs[jobId] = {
        status: 'error',
        error: 'Output file was not generated by Ghostscript.',
        timestamp: Date.now()
      };
      return;
    }

    try {
      const stats = fs.statSync(outputPath);
      const compressedSize = stats.size;
      const reductionPercent = ((originalSize - compressedSize) / originalSize * 100).toFixed(1);

      jobs[jobId] = {
        status: 'completed',
        originalName: originalName,
        originalSize: originalSize,
        compressedSize: compressedSize,
        savedPercent: Math.max(0, reductionPercent),
        downloadUrl: `/api/download/${compressedFilename}`,
        timestamp: Date.now()
      };
    } catch (statErr) {
      console.error(`[ERROR] Failed to stat output for job ${jobId}:`, statErr);
      jobs[jobId] = {
        status: 'error',
        error: 'Failed to access compressed output file.',
        timestamp: Date.now()
      };
    }
  };

  execGhostscript(gsArgs, handleResult);
});

// Progress & Status Check Endpoint
router.get(['/progress/:jobId', '/status/:jobId'], (req, res) => {
  const jobId = req.params.jobId;
  if (!jobId || !/^[a-zA-Z0-9_\-\.]+$/.test(jobId)) {
    return res.status(400).json({ error: 'Invalid jobId parameter.' });
  }

  const job = jobs[jobId];
  if (!job) {
    return res.status(404).json({ error: 'Job not found or expired.' });
  }
  res.json(job);
});

module.exports = router;
