const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const { jobs, upload, COMPRESSED_DIR, execGhostscript, getGsDiagnosticInfo } = require('./config');

// Diagnostics Endpoint
router.get('/diagnostics', (req, res) => {
  res.json(getGsDiagnosticInfo());
});

// Compress PDF Endpoint
router.post('/compress', upload.single('pdf'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No PDF file was uploaded.' });
  }

  const preset = req.body.preset || 'ebook';
  const originalName = req.file.originalname;
  const originalSize = req.file.size;
  const inputPath = req.file.path;
  const jobId = req.file.filename;

  jobs[jobId] = {
    status: 'processing',
    timestamp: Date.now()
  };

  res.json({
    success: true,
    status: 'processing',
    jobId: jobId
  });

  const compressedFilename = `compressed-${path.basename(req.file.filename)}`;
  const outputPath = path.join(COMPRESSED_DIR, compressedFilename);

  const gsArgs = [
    '-sDEVICE=pdfwrite',
    '-dCompatibilityLevel=1.4',
    `-dPDFSETTINGS=/${preset}`,
    '-dNOPAUSE',
    '-dQUIET',
    '-dBATCH',
    `-sOutputFile=${outputPath}`,
    inputPath
  ];

  const handleResult = (err) => {
    if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);

    if (err) {
      console.error(`[ERROR] Ghostscript failed for job ${jobId}:`, err);
      jobs[jobId] = {
        status: 'error',
        error: err.message || 'Ghostscript compression failed.',
        timestamp: Date.now()
      };
      return;
    }

    if (!fs.existsSync(outputPath)) {
      jobs[jobId] = {
        status: 'error',
        error: 'Output file was not generated by Ghostscript.',
        timestamp: Date.now()
      };
      return;
    }

    const compressedSize = fs.statSync(outputPath).size;
    const reductionPercent = ((originalSize - compressedSize) / originalSize * 100).toFixed(1);

    jobs[jobId] = {
      status: 'completed',
      originalName: originalName,
      originalSize: originalSize,
      compressedSize: compressedSize,
      savedPercent: Math.max(0, reductionPercent),
      downloadUrl: `/api/download/${compressedFilename}`,
      timestamp: Date.now()
    };
  };

  execGhostscript(gsArgs, handleResult);
});

// Progress Check Endpoint
router.get('/progress/:jobId', (req, res) => {
  const job = jobs[req.params.jobId];
  if (!job) {
    return res.status(404).json({ error: 'Job not found.' });
  }
  res.json(job);
});

module.exports = router;
