const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const AdmZip = require('adm-zip');
const { upload, UPLOADS_DIR, COMPRESSED_DIR, execGhostscript } = require('./config');

// Support both /pdf-to-image and /pdf-to-img
router.post(['/pdf-to-image', '/pdf-to-img'], upload.single('pdf'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No PDF file was uploaded.' });
  }

  const dpi = parseInt(req.body.dpi || '150', 10);
  const format = req.body.format || 'png'; // 'png' or 'jpeg'
  const originalName = req.file.originalname;
  const inputPath = req.file.path;

  const allowedDpis = [72, 150, 300];
  const allowedFormats = ['png', 'jpeg', 'jpg'];

  if (!allowedDpis.includes(dpi) || !allowedFormats.includes(format)) {
    if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
    return res.status(400).json({ error: 'Invalid conversion parameters.' });
  }

  const device = (format === 'jpeg' || format === 'jpg') ? 'jpeg' : 'png16m';
  const ext = (format === 'jpeg' || format === 'jpg') ? 'jpg' : 'png';

  const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
  const outputPattern = path.join(UPLOADS_DIR, `page-${uniqueSuffix}-%d.${ext}`);

  const gsArgs = [
    `-sDEVICE=${device}`,
    `-r${dpi}`,
    '-dNOPAUSE',
    '-dQUIET',
    '-dBATCH',
    `-sOutputFile=${outputPattern}`,
    inputPath
  ];

  execGhostscript(gsArgs, (error, stdout, stderr) => {
    // Delete input temp PDF file
    try {
      if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
    } catch (e) {
      console.error('Failed to delete input temp file:', e);
    }

    if (error) {
      console.error(`[Ghostscript Error] Conversion failed:`, stderr || error.message);
      return res.status(500).json({
        error: 'Ghostscript failed to convert the PDF file.',
        details: stderr || error.message
      });
    }

    try {
      const files = fs.readdirSync(UPLOADS_DIR);
      const prefix = `page-${uniqueSuffix}-`;
      const imageFiles = files
        .filter(f => f.startsWith(prefix) && f.endsWith(`.${ext}`))
        .sort((a, b) => {
          const numA = parseInt(a.replace(prefix, '').replace(`.${ext}`, ''), 10);
          const numB = parseInt(b.replace(prefix, '').replace(`.${ext}`, ''), 10);
          return numA - numB;
        });

      if (imageFiles.length === 0) {
        return res.status(500).json({ error: 'No image pages were generated by Ghostscript.' });
      }

      // Bundle into ZIP file
      const zip = new AdmZip();
      imageFiles.forEach((file, index) => {
        const filePath = path.join(UPLOADS_DIR, file);
        zip.addLocalFile(filePath, '', `page_${index + 1}.${ext}`);
      });

      const zipFilename = `converted-${uniqueSuffix}.zip`;
      const zipPath = path.join(COMPRESSED_DIR, zipFilename);
      zip.writeZip(zipPath);

      console.log(`[SUCCESS] Converted "${originalName}" to ${imageFiles.length} images. Packed into ZIP: ${zipFilename}`);

      res.json({
        success: true,
        pagesCount: imageFiles.length,
        downloadUrl: `/api/download/${zipFilename}`,
        imageUrls: imageFiles.map(f => `/api/preview/${f}`)
      });
    } catch (err) {
      console.error('Failed to process converted images:', err);
      res.status(500).json({ error: 'Failed to package converted images.' });
    }
  });
});

module.exports = router;
